### ISSUE TITLE
content on spreadsheet doc page

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/TimelineJS3#153]
http://timeline3.knightlab.com/docs/using-spreadsheets.html

This should link to Media Types, and not have the [bracketed text]

![screen shot 2015-06-22 at 2 09 14 pm](https://cloud.githubusercontent.com/assets/2432672/8290398/6edaa1be-18e8-11e5-92ef-360a309770f1.png)

For consistency J and K should be bolded.
![screen shot 2015-06-22 at 2 14 01 pm](https://cloud.githubusercontent.com/assets/2432672/8290486/fc90f51c-18e8-11e5-9e32-8d824bdf9f6d.png)

We also don't include column I and O and what those do.

**Comment by hbillings** [comment]
Mostly fixed. I and O are the display date and media thumbnail image rows, respectively. I can add the info for O, but no one ever clarified the display date for me (as per the google doc comment).

**Comment by thejordan** [comment]
@zachwise can you please clarify how and why someone would use the display date? Can I get an example please? Thank you!

**Comment by JoeGermuska** [comment]
the display date overrides any formatting TimelineJS would otherwise do based on the values of the start date and (optional) end date. 

This opens up a lot of flexibility, while still conforming to Timeline's need to have "real" dates for ordering events and scaling the timeline. 

For example, one might want to label the slides "day 1", "day 10", "day 45", or by week, or otherwise override Timeline's default date formatting without having to go to the lengths of creating an alternate language file.
