### ISSUE TITLE
Timeline height for each group

### ISSUE THREAD

**Issue by PhoenixGrey** [NUKnightLab/TimelineJS3#176]
When I have 10 groups displaying, the event title on the timeline can not be shown. In case, I have to set the height to 1200px, which cause the whole page to scroll. 
![group title](https://cloud.githubusercontent.com/assets/6336027/8868431/e6207344-320a-11e5-90f0-3a1ab0d3314c.png)

Is there a detour to make the group title displayed ? Such as changing css ?

**Comment by JoeGermuska** [comment]
If you need so many groups, you should probably give more height to the "timenav" section, instead of accepting the default height, which is 25% of the total height.

You may specify `timenav_height` or `timenav_height_percentage` in the options passed to the `VCO.Timeline` constructor. Both values should be integers: the first a pixel value, the second a number between 0 and 100. There is also a `timenav_height_min` option which can override either of those preferences.

At this time there is no support for setting this value in the "authoring tool"/iframe embed environment. You'll need to instantiate the Timeline in your own javascript and pass the options there. See [this documentation](http://timeline3.knightlab.com/docs/instantiate-a-timeline.html) for more info.

We recognize that there is still documentation which needs writing about the options which can be passed, etc. (see #147)
