### ISSUE TITLE
All events at the same instant leads to divide-by-zero.

### ISSUE THREAD

**Issue by faridjame** [NUKnightLab/TimelineJS3#182]
Here is the JSON string I'm trying to use: http://newzt.ztwealth.com/api/timeline/category_posts/

Up until the first 4 events, it works fine; however, adding the fifth event, causes the following js error and the timeline is not displayed: 

    Error: TypeError: i[l] is undefined
    Source File: /TimelineJS3/compiled/js/timeline-min.js
    Line: 13

I don't really see anything funky in the content of the 5th event, any idea why I'm getting this error and how to resolve it?

Thank you

**Comment by JoeGermuska** [comment]
Ultimately, this is happening because all of your events are on the same exact date. There's [a divide-by-zero error](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/timenav/VCO.TimeScale.js#L34-L38) which only becomes fatal when Timeline runs out of free rows and tries to manage overlapping events.

It doesn't actually work correctly before then, as the labels on the axis don't work.

So, obviously we need to fix the divide-by-zero, but also, do you really intend for all of your events to be on the same date?

**Comment by faridjame** [comment]
I hard-coded all the events to be on the same date just for testing. I'll go ahead and change them to their actual dates. Thank you very much for looking into this.

**Comment by JoeGermuska** [comment]
with e8177a3 and 8a45033 this should be fixed.
