### ISSUE TITLE
Multilanguage support for BCE

### ISSUE THREAD

**Issue by FraLa** [NUKnightLab/TimelineJS3#190]
Thanks for this fantastic work.
One issue that you can improve form my point of view is the Multilanguage support for negative_year. At the moment it is the static string “BCE” but in other languages this can differ from English e.g. in German it is “v. Chr.”

see timeline.js
negative_year: { // if either of these is specified, the year will be converted to positive before they are applied
        	prefix: '', 
        	suffix: 'BCE' // in German it would be "v.Chr." in Spain "a. C."

**Comment by JoeGermuska** [comment]
Yes. It's actually not a static string: it can specified in the translation files. The template for English [can be seen in the en.json translation file](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/language/locale/en.json#L76-L84).

Since our language fluency is limited, we've been dependent upon community contributions. The translations we have are based on the original TimelineJS, which didn't support localized era labels. 

The relevant file here would be https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/language/locale/de.json Can you submit a pull request?

**Comment by JoeGermuska** [comment]
I'm going to close this specific issue. Pull requests to add era labels for various languages are welcome!
