### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#210]
Let's rethink the accordion styles used on current products, though. It's not super scannable and we can do better.

**Comment by JoeGermuska** [comment]
I agree. It's also hard to link directly to answers. Also, now that we're out of the all-in-one-page design approach, we can make a separate `timeline3.knightlab.com/faq/` page

**Comment by JoeGermuska** [comment]
"Can I make images clickable?"
"How can I format text/add line breaks/bold/italic?"
(will add more as they come up)

**Comment by hbillings** [comment]
- Licensing
- Date/time formatting
- Data storage (let's demystify where the data from the spreadsheet goes and to whom it is accessible)
- Issues embedding on Squarespace/WordPress/etc?
- Using Timeline offline/printing
- Browser support (not really frequently asked, but nice to have)

**Comment by hbillings** [comment]
Page is stubbed out, but I'm leaving the ticket open until we put some content in it.

**Comment by JoeGermuska** [comment]
I added support for permalink questions and for dynamically populating the "jump to" section, because I took out one section for now.

I also fleshed out some questions and found a problem using a `<li>` in an answer. One problem I fixed by attaching the *A* to `nth-child(2)` instead of `last-child` (`nth-child` is supported back to IE9) but the li still looks janky. @hbillings Can you take a look, or if you think lists don't belong, suggest a different way to answer that?

Otherwise, I'm about satisfied to make it live and add more answers as we move forward.

**Comment by JoeGermuska** [comment]
Also I added more questions and answers, so another pair of editorial eyes is welcome...
