### ISSUE TITLE
Inconsistent Navigation

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#250]
![image](https://cloud.githubusercontent.com/assets/741789/10075268/7564291e-629a-11e5-9baa-4c4d6adcd12e.png)
![image](https://cloud.githubusercontent.com/assets/741789/10075271/7def66f2-629a-11e5-8748-8021e12ba7e7.png)
Some things page jump, some things go to other pages. It's extremely disorientating.

**Comment by zachwise** [comment]
This is probably worthy of a f2f conversation btw.

**Comment by scott2b** [comment]
This is also an issue with StoryMap navigation (Examples link scrolls, others do not). I do not think the issue is scroll vs. page links so much as the fact that the scroll uses javascript and does not full-follow to the hash-link, thus breaking the back button.

@shortdiv we will want to tackle the consistency of primary navigation as an element of OrangeLine across all of our products. If we want to have scroll navigation, then there should be a navigation trail -- ie. the back button should work regardless of scroll or intra-page navigation.

@zachwise would this suffice for consistency of navigation, or do you think the problem is more than what I am seeing?

**Comment by scott2b** [comment]
this appears to be fixed since orangeline cutover
