### ISSUE TITLE
Remove 'state' variables from 'options' documentation'

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#272]
@JoeGermuska it looks like we need separate `state` variables from `options`, so that it's clear to developers what the actual options are. This has come up several times, most recently with #271 That will be a fair amount of work, since it will basically affect every class.

**Comment by jacalata** [comment]
Perhaps a quick intermediate step could be adding a note to the docs at http://timeline.knightlab.com/docs/options.html highlighting which variables developers shouldn't be touching?

**Comment by JoeGermuska** [comment]
At least for starters, we should just remove state variables from the documentation and indicate that there's no guarantee for consistent behavior of variables that people find in the code which aren't formally documented. This is pretty standard with API documentation.

@zachwise can you identify those which should be removed?

**Comment by JoeGermuska** [comment]
I think Zach's original idea was more complicated, but simply removing certain things from our docs and making it clear that just because people can read the source code doesn't mean that they should take advantage of undocumented features is easy, so I adjusted the title, raised the priority, and marked this as a `current` milestone concern because I think fixing the doc is important.

**Comment by JoeGermuska** [comment]
I've removed `skinny_size` and `medium_size` from the docs on the assumption that they are also not meant to be user configured. @zachwise please correct me if I'm wrong, and if you have time, note any others you can recommend for removal.

**Comment by scott2b** [comment]
fixed by removal of skinny_size and medium_size
