### ISSUE TITLE
language file not loaded

### ISSUE THREAD

**Issue by ilomedia** [NUKnightLab/TimelineJS3#306]
using the following code, the language file tries to load from the site domain instead of cdn.knightlab.com when caches are empty.
everything works fine as soon as the page has been visited once

```javascript
timeline = new TL.Timeline(
	'tab3',
	'https://docs.google.com/spreadsheets/d/xxxxxxxxxxxxx-_I35S0/pubhtml',
	{
		language:'fr',
		initial_zoom: 1
	}
);
```

result : GET http://myhost.tld/locale/fr.json 404 Not Found 138ms

**Comment by phmassa** [comment]
same problem for me, but work with other languages

**Comment by JoeGermuska** [comment]
Your example does not indicate how you are loading the javascript, but if you have copied it to your local site, then Timeline is behaving as expected. It loads auxiliary files from the same location where `timeline.js` (or `timeline-min.js`) is loaded.

You can override this by setting the `script_path` option, for example, to `https://cdn.knightlab.com/libs/timeline3/latest/js`

You can also specify a fully-qualified path to a language JSON file, instead of a language code, for example, `https://cdn.knightlab.com/libs/timeline3/latest/js/locale/fr.json`  This is something you are more likely to use if you wanted your own translation file, perhaps to override the date formats or the like.

**Comment by ilomedia** [comment]
The script is loaded from your CDN therefore it DOES NOT behave as expected : 

<link rel="stylesheet" href="//cdn.knightlab.com/libs/timeline3/latest/css/timeline.css" />
<script type="text/javascript" src="//cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>

i do not use any custom language file. script_path fixes the problem but this is only a workaround
