### ISSUE TITLE
3.3.10 introduced breaking change

### ISSUE THREAD

**Issue by jeshan** [NUKnightLab/TimelineJS3#317]
Hi,
I just noticed that my timeline is no longer working since yesterday 2015-12-02.

This works:
http://cdn.knightlab.com/libs/timeline3/3.3.9/embed/index.html?source=1kABwU2-m9OZav6PtW1xAiIbQXBe0EdClCVnDy4aKqvM&font=Default&lang=en&debug=true&initial_zoom=2&height=650

whilst this doesn't:
http://cdn.knightlab.com/libs/timeline3/3.3.10/embed/index.html?source=1kABwU2-m9OZav6PtW1xAiIbQXBe0EdClCVnDy4aKqvM&font=Default&lang=en&debug=true&initial_zoom=2&height=650

**Comment by jeshan** [comment]
This is likely going to break every timeline which is retrieving "latest" instead of a specific version.

**Comment by zachwise** [comment]
@JoeGermuska it appears the latest header check that was added makes the old spreadsheet templates break.

**Comment by JoeGermuska** [comment]
Time for me to admit that people will do crazy things to the spreadsheets and not notice that stuff they put in them doesn't show up, and not mind.

This has been backed out in 3.3.11 which has also been deployed to latest. We'll implement a different strategy for warning people that they've made changes to the spreadsheet which will result in Timeline not showing certain data.

**Comment by jeshan** [comment]
I don't get it. What did I do wrong?

**Comment by JoeGermuska** [comment]
The changes were intended to verify that the spreadsheet headers were unchanged from the template. You probably deleted columns or changed the header in a column. If you change the header text for a column, that data is ignored by Timeline, because it doesn't receive the data positionally.  

The only column which is strictly required for a timeline to function is the start year. We've seen people change other column headers, put data in that column, and apparently never notice that the data they put there is not showing up. We can just accept this, but we thought it would be helpful to warn people. 

Unfortunately, the way Timeline is organized, (a) it's difficult to give people really clear information about what to do and not do, and (b) it's hard to do something which is a "warning" but not a "fatal error".

The only really "fatal" error is when people enter data which simply cannot be parsed into a date. Making that a fatal problem has been a headache for some people, so we should also go back to simply skipping those rows and letting the validation system proposed in #318 serve as notice.
