### ISSUE TITLE
Header Row has been modified. Timeline configuration has no events - Google Docs

### ISSUE THREAD

**Issue by rebootcode** [NUKnightLab/TimelineJS3#324]
I am constantly getting error as written on timeline.

This is the DOC file, i am trying to use. It is nothing but just copy of demo spreadsheet plus 1 extra event.

DOCFILE URL: https://docs.google.com/spreadsheets/d/1_-07TKshla99NAfMlpcBYt8q1QkblkQa14sTay8uL_0/pubhtml

Can you please let me know, what am i Missing ?

Thanks

**Comment by JoeGermuska** [comment]
As the message states, the header row has been modified. 

![image](https://cloud.githubusercontent.com/assets/46313/11936289/6dfdba14-a7d2-11e5-8af9-d16d17d43b53.png)

The A1 cell must read "year" as it does in [the  Google Spreadsheet template](https://drive.google.com/previewtemplate?id=1pHBvXN7nmGkiG8uQSUB82eNlnL8xHu6kydzH_-eguHQ&mode=public). If the headers are changed, TimelineJS is not able to read data.

For future reference, this sort of question is better directed to our [online support system](http://knightlab.zendesk.com) rather than opening a GitHub issue.
