### ISSUE TITLE
Events are not fired

### ISSUE THREAD

**Issue by CZechBoY** [NUKnightLab/TimelineJS3#347]
Hi,
I have this code:
`
$.getJSON(url, function (timelineData) {
    new TL.Timeline('my-timeline', timelineData, {
        language: 'cz'
    }).on('loaded', function () {
        bindEvents($('#my-timeline'));  // this is not called
    });
});
`

I'm using _master/compiled/js/timeline.js_ from 22-02-2016.

Any ideas?
Thanks

**Comment by JoeGermuska** [comment]
Please post support questions to knightlab.zendesk.com  Include a link to a page which demonstrates the issue, if at all possible.  

Note, there is no reason to make your own JSON call. Timeline will fetch the data for you:
>*Creating your own JSON*
>If you are retrieving JSON from a URL, you can simply use that URL as the second argument, just as if you are loading data from a Google spreadsheet. If instead you have something in your page which will put the data together, you can also pass a JSON object as the second argument.

http://timeline.knightlab.com/docs/instantiate-a-timeline.html#in-page-json

I just tried something which set a 'loaded' event handler after instantiating a timeline and it did fire. 
Of course, it's possible that there's a race condition involved with binding the 'loaded' callback, so that a bug is intermittent. But until we see a case where the issue is coming up, we can't invest a huge amount of time hunting for it.

**Comment by CZechBoY** [comment]
I'm using own json call because Timeline showing bad error message if no events are in the json. And if there is some error or something happen I want to not show the timeline.

I will build demo page with that bug and post it here.

**Comment by JoeGermuska** [comment]
It's the same JSON whether you fetch it with your own call or Timeline gets it.

**Comment by CZechBoY** [comment]
Yes, but if I do custom call I can define that timeline should be hidden. If the call makes timeline then ugly error is shown.

**Comment by JoeGermuska** [comment]
You could, if you check the data that comes back from your JSON, yes. Your code doesn't do that.
