### ISSUE TITLE
Convert imgur to embed

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#377]
Apparently our conversion of imgur URLs to direct ("hotlinked") images is against their terms of service. This is causing people to get broken images with 403 status in the console.

I guess we'll have to switch to use their embed code.

**Comment by mazhang2718** [comment]
I got the imgur embed to mostly work a while back, but there's some issues with the display that I still can't figure out. It seems that although the embed is horizontally responsive, the vertical sizing overrides all of the containers it's in.

<img width="1191" alt="screen shot 2016-10-12 at 1 17 48 pm" src="https://cloud.githubusercontent.com/assets/12781097/19322446/b8afa2f8-907e-11e6-9af3-69724401d68e.png">

When I tried to manually adjust the vertical size, it cuts off the bottom instead of resizing...

<img width="1181" alt="screen shot 2016-10-12 at 1 19 13 pm" src="https://cloud.githubusercontent.com/assets/12781097/19322466/d0ed186e-907e-11e6-87b0-1b145ac104fa.png">
