### ISSUE TITLE
Slides stack on top of one another

### ISSUE THREAD

**Issue by dawnkayla** [NUKnightLab/TimelineJS3#381]
We've been using this slideshow at Ballotpedia, but keep having the same issue that may be due to our use of Mediawiki. More often than not our timelines show up with each slide stacked on top of one another. Is there a fix to this?

Page: https://ballotpedia.org/Clean_Power_Plan#tab=Timeline
Code: ``<html><iframe src='//cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1Je5FQRo14KWhwmkc5xFQx7mUzkcWtO3i60B5dvnT5QI/pubhtml?widget=true&amp;headers=false"height=650' width='100%' height='650' frameborder='0'></iframe></html>``
Google sheet: https://docs.google.com/spreadsheets/d/1Je5FQRo14KWhwmkc5xFQx7mUzkcWtO3i60B5dvnT5QI/edit#gid=0

Example:
![screen shot 2016-07-19 at 5 21 40 pm](https://cloud.githubusercontent.com/assets/10080638/16971123/e8fe3c30-4dd5-11e6-887a-dbb393a7a37c.png)

**Comment by JoeGermuska** [comment]
@dawnkayla the problem is that the timeline is initializing while the tab is not visible/rendered. 

Unless we figure out a secure way to support `window.postMessage()` from any site which hosts a timeline, you have to manage this yourself. There are a few ways:

1) Use javascript and CSS to change the size of the iframe when the tab becomes visible. You could just set the width to 99% or something.

2) Embed the timeline using javascript instead of an iframe. See http://timeline.knightlab.com/docs/instantiate-a-timeline.html for more info. You could then defer actually doing the instantiation until that tab is made visible, or you could call `timeline.updateDisplay()` after the tab is made visible.

3) use javascript to set the `src` of the iframe only when the tab is made visible

hope this helps.

**Comment by JoeGermuska** [comment]
FWIW, I just went and read some more, and I have trouble seeing what risk we expose ourselves to if we are merely listening for a message like `resize` from the host page which contains the iframe. It would still require javascript, which will be challenging for some of our users.

**Comment by dawnkayla** [comment]
@JoeGermuska Thank you very much! We will look into these options. I appreciate your time.
