### ISSUE TITLE
Problem with Polish translation and time

### ISSUE THREAD

**Issue by Azot94** [NUKnightLab/TimelineJS3#445]
https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1dZK-6Rn68JPKhLAsHCoJujKPg456Ql8pA-5hpOQzvpE&font=Default&lang=pl&initial_zoom=2&height=650

http://imgur.com/a/EbMqi

**Comment by thehandsomepanther** [comment]
@Azot94 can you explain exactly what's wrong with the translation and time, and could you share your spreadsheet?

**Comment by Azot94** [comment]
> Can you explain exactly what's wrong with the translation and time

I don't know how to explain it. The problem is with the style of displaying format data and time if u set time parameter. See examples.

Format date and time (default) http://imgur.com/Qpx7PRx - Everything is correctly.

Format date and time (Polish) http://imgur.com/PvjpoGN - It looks ugly

Format date and time (German) http://imgur.com/ooVXhtL - It looks ugly

> Could you share your spreadsheet

https://docs.google.com/spreadsheets/d/1dZK-6Rn68JPKhLAsHCoJujKPg456Ql8pA-5hpOQzvpE/edit#gid=0

**Comment by thehandsomepanther** [comment]
It appears that this is how translations are meant to appear, and that the line breaks come from <br> tags which are present across all translations to control layout on the time axis. The English "translation" appears differently because Timeline uses English as the default and so doesn't make a network call to fetch the json.
