### ISSUE TITLE
Icons are not displayed correctly

### ISSUE THREAD

**Issue by Simone-cogno** [NUKnightLab/TimelineJS3#462]
I have included the css and the js: 

`<link title="timeline-styles" rel="stylesheet" href="node_modules/TimelineJS3/compiled/css/timeline.css" type="text/css">`

`<script type="text/javascript" src="node_modules/TimelineJS3/compiled/js/timeline.js"></script>`

And I added the embed timeline:
`<div id="timeline"></div>`

But the icon for slide to right and left are showed with an empty square (so seems that icons are not loaeded).

Do I need to include other css? 

Edit: If I include the CDN instead then it works.

Version TimelineJS3 3.4.7

**Comment by scott2b** [comment]
@Simone-cogno am I understanding correctly that this is working for you now?

**Comment by amilcarrey** [comment]
> Edit: If I include the CDN instead then it works.

Yes, if you put the link with CDN instead css file path works fine because the css and the icons are in the same server. If you take a look on into css file you will found `@font-face{font-family:tl-icons;src:url(icons/tl-icons.eot)` , that means that the file it is looking for a font `icons.eot` into `icons `folder. That is, if you have a folder and the icon inside then will work. 

It is a two possible solutions:
1. Put the cdn instead a static css file `<link title="timeline-styles" rel="stylesheet" href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">`

2. Find the files and import them to your project and modify the css with the url of your project. That is: 
`@font-face{font-family:tl-icons;src:url(**icon-folder-in-your-project**/**tl-icons.eot**)`  

(If I can find them i will share wit you).  

@scott2b @Simone-cogno 

Cheers!

**Comment by ajaxStardust** [comment]
i encounter the missing tl-icon.eot error using a local copy of timeline.css (likewise, as above, presumed). 

Does anyone yet have a URL for the .eot (or wotf, ttf, ..)

i recognize that this thread was closed Only two-thousand nine-hundred eighty-four days ago. 

[ have a heart / hurry hard ]
