### ISSUE TITLE
version missing from timeline.js and timeline-min.js

### ISSUE THREAD

**Issue by fastfasterfastest** [NUKnightLab/TimelineJS3#539]
The release version (e.g. 3.5.1) seems to be missing from timeline.js and timeline-min.js.

E.g., the banner comment in timeline.js release 3.5.1 contains `TimelineJS - ver. 2017-03-31-15-29-59 - 2017-03-31` but not the release version.  And, these dates don't seem to correspond to the date the release was built.
It would be useful if the release version was readily available in timeline.js and timeline-min.js, e.g. in the banner comment (as it is in e.g. http://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js).  And/Or, perhaps the `TL.VERSION` should be updated and contain the release version.

**Comment by JoeGermuska** [comment]
Can you clarify where you find that banner comment? 

The only official version numbers are those on `cdn.knightlab.com` and the corresponding tags in the git repository. The presence of "build artifacts" in the repository (specifically in `/compiled/`) is more a side effect of legacy development practices than an explicitly supported feature. 

I can see where this may be confusing to outsiders, and its something about which we are open to conversation, but one of our general principles is that code which is the result of a build script ought not be included in repositories, because it leads to meaningless merge conflicts and repo bloat. Therefore, our automated build process uses the `build` directory, which is `.gitignore`'d.

That said, we haven't fully been able to give up the convenience of having the `/compiled/` directory which allows for certain kinds of testing, so from time to time we copy updated versions of the code into that directory. 

Finally, I haven't yet seen (although I haven't looked *that hard*) a straightforward way to change things in the code (like `TL.VERSION`) as part of a scripted build, manage the repository state (that is commit that change with the correct git tag) and otherwise keep everything orderly without a hands-on, multi-step process. That has led to `TL.VERSION` not being reliable, but since the vast majority of TimelineJS's use is through the hosted embed, we have let that slip.

We could make updating the `/compiled/` directory something which happens whenever we stage versions for the `cdn` without a lot of trouble, if that would help.  And we welcome pointers to good strategies for changing something like `TL.VERSION` smoothly in a scripted build, including git commits and correct tagging.  Alternatively, we could try to make it a human step before the CDN build, but experience shows that human step is easy to forget.

**Comment by fastfasterfastest** [comment]
>  Can you clarify where you find that banner comment?

In timeline.js - https://github.com/NUKnightLab/TimelineJS3/blob/master/compiled/js/timeline.js
In timeline-min.js - https://github.com/NUKnightLab/TimelineJS3/blob/master/compiled/js/timeline-min.js

> the vast majority of TimelineJS's use is through the hosted embed,

Our public facing web site does indeed use timeline-min.js from cdn.knightlab.com.  But, for our "CMS"/backend system we use a self-hosted version which we get from here on GitHub.

> The presence of "build artifacts" in the repository (specifically in /compiled/) is more a side effect of legacy development practices than an explicitly supported feature

>We could make updating the /compiled/ directory something which happens whenever we stage versions for the cdn without a lot of trouble, if that would help.

Yes, I think updating `/compiled` to contain the "build artifacts" of releases would be useful.  I had assumed `/compiled` already did so... are you saying it does not (necessarily) do so?

**Comment by fastfasterfastest** [comment]
> Yes, I think updating /compiled to contain the "build artifacts" of releases would be useful. I had assumed /compiled already did so... are you saying it does not (necessarily) do so?

I now see that `/compiled` was not updated for 3.5.1.  And maybe not since 3.4.8 or so.

We started using TimelineJS when it was published on https://github.com/NUKnightLab/TimelineJS.  And there it is stated:
> If you need to serve copies of the files from your own server, use the entire contents of the "/build/" directory of our GitHub repository

When TimelineJS transitioned to TimelineJS3, and we switched to use TimelineJS3, I guess we didn't pay close attention and probably assumed the old `/build` in TimelineJS was now called `/compiled` in TimelineJS3 and was updated whenever a new release was made.  For those of us that self-host TimelineJS3, I think it would be very helpful if you could update `/compiled` when you create a new tag/release.

**Comment by scott2b** [comment]
To clarify. compiled is not always updated with every release. In principle, we try to keep it updated. In practice, it does not always happen

**Comment by JoeGermuska** [comment]
As of that version, TimelineJS now uses more modern JS build tooling, so we no longer maintain the `/compiled/` version. We'll remove it from the repository soon to clarify.

Options for getting a compiled TimelineJS:
* [Install from npm](https://www.npmjs.com/package/@knight-lab/timelinejs)
* [download a ZIP of the distribution from our cdn](https://cdn.knightlab.com/libs/timeline3/latest/timeline3.zip)
* [compile from source](https://github.com/NUKnightLab/TimelineJS3/blob/master/CONTRIBUTING.md#building)

Hope this helps.
