### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by jefrice** [NUKnightLab/TimelineJS3#572]
Here is my code:

```
<script type="text/javascript">
	var timeline_json = $.getJSON( "http://localhost:3000/users/2.json", function() {console.log( "success" );})
	var additionalOptions = {
              start_at_end: true,
              default_bg_color: {r:0, g:0, b:0},
              timenav_height: 250,
              height: 600
            }
	var timeline = new TL.Timeline('timeline-embed', timeline_json, additionalOptions);
</script>                            
<div id='timeline-embed' style="width: 100%; height: 1000; frameborder: 0;"></div>
```

The JSON comes back fine -- but I get a strange error: 
timeline.js:13087 Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at NewClass.initialize (timeline.js:13087)
    at new NewClass (timeline.js:2404)
    at 2:135

**Comment by jefrice** [comment]
user error. I figured it out.

**Comment by f1234k** [comment]
For future reference, if someone comes across this:

In my case, this specific error was caused because the javascript to instantiate the timeline came before the rendering of the html. So, if you're not using jquery with document ready and stuff, make sure that the javascript is after the html markup.
