### ISSUE TITLE
Error: unable to read your google spreadsheet

### ISSUE THREAD

**Issue by igorfilko** [NUKnightLab/TimelineJS3#606]
Followed your tutorial step by step to the letter, copied template to new spreadsheet, deleted the empty rows, published, copy&paste url into your form on page http://timeline.knightlab.com/#make
click your preview button - error
click your preview in new window button - error

error is: ERROR:  Unable to read your Google Spreadsheet. Make sure you have published it to the web.
you can recheck it on 
https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cgU_KfjJgxZPWYDzzj5jJd-h_sCY_BwdF06rI-MDkwo&font=Default&lang=en&initial_zoom=2&height=650

spreadsheet is on https://docs.google.com/spreadsheets/d/1cgU_KfjJgxZPWYDzzj5jJd-h_sCY_BwdF06rI-MDkwo/edit?usp=sharing

Console reveals:
timeline-min.js?2.24:10 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
$.ajax @ timeline-min.js?2.24:10
timeline-min.js?2.24:10 Failed to load resource: net::

any ideas?

**Comment by JoeGermuska** [comment]
Works for me

![image](https://user-images.githubusercontent.com/46313/52226066-92c04380-2871-11e9-9819-5d8d69b250f0.png)

For future reference, please note that GitHub issues should be reserved for software development issues. For user support, please use our [Zendesk support system](https://knightlab.zendesk.com/hc/en-us/requests/new).  If you're not sure, start with Zendesk, and we'll create a GitHub issue if appropriate.

**Comment by AnaPenha** [comment]
Dear Joe,
I´ve been using Timeline for three years in my on line courses without a problem, but now I think there must be a problem with the Spreadsheet templates because they are not working. I see the same error message as Igorfilko: Unable to read your Google Spreadsheet. Make sure you have published it to the web.
https://docs.google.com/spreadsheets/d/1ewo30GZq5Lm3rEc7bxMbdV7tjn3kTDesLD0m_uwRA3w/edit#gid=0 
I don't understand why it is not working, I am doing exactly the same as last years. Can you help me please?

**Comment by JoeGermuska** [comment]
As noted above, we strongly prefer to handle support requests through our [Zendesk support system](https://knightlab.zendesk.com/hc/en-us/requests/new), where we have a regular process for making sure that requests are handled.

That said, when I go to this variant URL:
https://docs.google.com/spreadsheets/d/1ewo30GZq5Lm3rEc7bxMbdV7tjn3kTDesLD0m_uwRA3w/pubhtml

I get the message that your spreadsheet is not published. Please review the specific instructions on the Timeline website. Specifically, understand that "sharing" with "anyone with the link can view" is not the same as "publish to the web", and for TimelineJS, you must "publish to the web."

**Comment by AnaPenha** [comment]
Thank you very much for your rapid response, Joe.
I was just following this intruction on your web: " The following has changed as of 18 July 2017!
Close the 'Publish to the web' window. Copy the URL for your Timeline from the browser's address bar. It should look something like this:
https://docs.google.com/spreadsheets/d/1xuY4upIooEeszZ_lCmeNx24eSFWe0rHe9ZdqH2xqVNk/edit#gid=0 
Disregard the URL that appears in the "publish to the web" window. It used to be used below, but changes to Google mean that you'll get an error if you use it now."
That is why I haven´t published my timeline before embeding it in my course. 
Now is working, but that message should not be there, I suppose.
Best regards from Spain

**Comment by JoeGermuska** [comment]
Thanks for the follow-up. Maybe we haven't written the message as clearly as we could for non-native English speakers.  One must still publish to the web, but the URL which is shown right after taking that step, which one might assume is the one to use for configuring TimelineJS, does not work, because of Google's changes.
