### ISSUE TITLE
No styling but working icons

### ISSUE THREAD

**Issue by JeroenDeDauw** [NUKnightLab/TimelineJS3#622]
I created an extension to embed these timelines into MediaWiki. This is working great except that the timeline comes with a bunch of CSS that overrides the styling of the wiki. For instance it makes links red, while they normally are blue.

Is there a way to have the timeline show up in working fashion without special styles for slide content?

I saw the docs that I can use the `base_class` option to avoid styles being applied. This does what I want but unfortunately also breaks the styling of the icons, which then show up above the timeline. 

![image](https://user-images.githubusercontent.com/146040/62488872-a3705880-b7c5-11e9-98a1-bf572cfe792a.png)

Correct display for comparison:

![image](https://user-images.githubusercontent.com/146040/62488906-b7b45580-b7c5-11e9-854f-787834309a73.png)

In some cases the icons show up way above the timeline.

**Comment by JoeGermuska** [comment]
To clarify, when you say "it makes the links red," you're just talking about the hover state, right? 

TimelineJS was designed with extremely specific CSS selectors.  While this was a non-issue in the typical iframe embed use-case, in retrospect, it was probably a mistake, but changing it casually now could impact a number of existing installations  

Because of those specific selectors, the docs about using `base_class` are wrong and should be amended; as you found, most CSS selectors depend upon being under `.tl-timeline` so changing the base class requires providing an entirely new stylesheet; the only value, I guess, would be if there were two timelines on one page with different styles, which is probably not something we'd recommend.

The most straightforward solution today would be to override the CSS styles for links in the page (below), or in a CSS sheet which takes priority over the Timeline CSS, or to override the source and recompile the CSS from the LESS files in the Git repository.  Not my favorite suggestion, but it may be a while before we are able to chart a better plan.

```
.tl-timeline p a {
 color:#666;
 text-decoration:underline
}
.tl-timeline p a:hover,
.tl-timeline p a:focus {
 color:#c34528
}
@media (-webkit-min-device-pixel-ratio:1.5),(min-resolution:144dpi) {
 .tl-timeline p a {
  text-decoration:underline;
  background-image:none;
  text-shadow:none
 }
 .tl-timeline p a:hover,
 .tl-timeline p a:focus {
  color:#c34528;
  text-decoration:underline
 }
}
```

**Comment by JeroenDeDauw** [comment]
> To clarify, when you say "it makes the links red," you're just talking about the hover state, right?

Unfortunately not. The first screenshot here is from a page where I used `base_class`. The text styling is as desired but the icons are broken. The second screenshot has the default behavior, which makes the link very much not in line with the wikis styling.

![image](https://user-images.githubusercontent.com/146040/62562739-f7d90e00-b881-11e9-977d-9fc148ffef14.png)

![image](https://user-images.githubusercontent.com/146040/62562658-e6900180-b881-11e9-8d21-a0a3c77465c8.png)

Using the provided CSS snippet does not really work for my case since I can't hardcode the styles. They are already set by the wiki software and vary based on installed skins and user preferences.

Having a version of timeline.css that does not have the problematic bits in there would be fantastic. I tried simply removing things from the compiled version I have though that does not work since it is many things spread over a 70k character long line of CSS. I have never worked with LESS and don't know how to compile it, and really don't have time to look into that for the task I am working on.

**Comment by JoeGermuska** [comment]
This is approaching something more like a tech support question than a proper Github issue. If you'd like to send a link to a page demonstrating the condition you're working on to us at support@knightlab.zendesk.com we can investigate further.
