### ISSUE TITLE
undefined variable in 3.7.0?

### ISSUE THREAD

**Issue by ccurvey** [NUKnightLab/TimelineJS3#643]
this may be coincidence, but....

timeline has recently (not sure when) stopped working on my site, and is throwing a JS error

```
Uncaught TypeError: i is undefined
    $e Timeline.js:64
    <anonymous> 964893:1275
```

I see that that there was a new tag created for 3.7.0 yesterday, and since I'm fetching the code from the CDN at https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js , it's making me suspicious.

of course, I can't explain why I'm getting a message about "i" when there is nothing like that near line 64.

**Comment by JoeGermuska** [comment]
This is not a coincidence. We introduced a small regression with yesterday's update. It will be fixed with the next release, but in the meantime, you can work around it by passing an empty "options" object in the Timeline constructor.

That is, I'm assuming you're not using our embed, but using something like described on our [Integrate Timeline using Javascript](http://timeline.knightlab.com/docs/instantiate-a-timeline.html) page. 

It has this:
```
        timeline = new TL.Timeline('timeline-embed',
          'https://docs.google.com/spreadsheets/d/1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI/pubhtml');
```

if you change it to this, it should work until the new fix is deployed.

```
        timeline = new TL.Timeline('timeline-embed',
          'https://docs.google.com/spreadsheets/d/1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI/pubhtml', {});
```

**Comment by ccurvey** [comment]
Perfect.  Thank you!
