### ISSUE TITLE
Background Image support for source from Google Drive

### ISSUE THREAD

**Issue by ynynl** [NUKnightLab/TimelineJS3#648]
I use images from my google drive. Currently I get the link via https://drive.google.com/uc?export=download&id=11AaJMkXJ7_QpgH3e2nLbY2xBIVvFcSKK to convert the google drive shareable link to a export link. The link works on Media column but always fail on background column.

For example: the link of image https://drive.google.com/uc?export=download&id=11AaJMkXJ7_QpgH3e2nLbY2xBIVvFcSKK is working within Media column, but no show if it's put in the Background column.

**Comment by JoeGermuska** [comment]
This is because, while TimelineJS can be quite flexible about what it presents in the "media" portion of a slide, the "background" must strictly be an image; no other media-type works.

TimelineJS uses a simple pattern matching process to determine how to handle different media values, and, further, to recognize which ones are suitable as use for background images (and media thumbnails, for what it's worth.)  

For background images and media thumbnails, unless the URL is recognized as from Flickr or another specialized media type that is known to provide images, the URL must end in a standard image filename extension. 

Thus, a "hack" that will work in this case is to add `#.jpg` at the end of your URL, which will be ignored by Google, but which will satisfy TimelineJS.  That is, for your background, with your example URL, use:
`https://drive.google.com/uc?export=download&id=11AaJMkXJ7_QpgH3e2nLbY2xBIVvFcSKK#.jpg`

Perhaps TimelineJS should just assume that an otherwise "unclaimed" URL for backgrounds/thumbnails is an image, but in the meantime, this will get the job done.
