### ISSUE TITLE
Text field HTML removing target="_blank"

### ISSUE THREAD

**Issue by jimmykl** [NUKnightLab/TimelineJS3#649]
I'm using links in the text on a timeline and would like them to open in a new tab but the target attributes are being stripped out between the google sheet and don't appear in the timeline HTML – is this intentional and is there a way to retain them?

**Comment by JoeGermuska** [comment]
this is "intentional," in the sense that it's a  default setting of the "HTML sanitizer" implmented [since TimelineJS 3.7.0.](https://knightlab.northwestern.edu/2020/07/09/timelinejs-update/index.html)

I assume you're not using the embedded iframe? That page has a `<base target="_blank">` tag which papers over the issue.

I've started poking around a bit to see what, if any, security implications there might be with permitting the `target`  attribute for links. I can't think of any, but I'm not the most  devious-minded. 

For now, if you can use a `<base>` tag, that's the recommended work-around. I'll try to push ahead on the research sooner and come back with a decision about permitting `target`  attributes in sanitized markup.

**Comment by jimmykl** [comment]
Thanks @JoeGermuska I appreciate putting security first.

In this case the timeline is being created from javascript [in some other content](https://www.nzonscreen.com/about) so I can't use a base tag unfortunately.

It's not a showstopper by any means but if there was a flag which could be set to allow target attributes I would use it :)

**Comment by JoeGermuska** [comment]
Since you're instantiating the thing in your own javascript, here's a workaround:

```javascript
document.getElementById('timeline-embed')
   .querySelectorAll('a')
   .forEach(function(elem) { 
      elem.setAttribute('target','_blank')
   })
```

**Comment by jimmykl** [comment]
Fantastic thank you @JoeGermuska

**Comment by JoeGermuska** [comment]
Re-opening this until we make an explicit determination about permitting 'target' on `a` tags, since not everyone will be able to use the Javascript workaround.

**Comment by JoeGermuska** [comment]
There are [definitely cautions about opening new windows/tabs from links](https://mathiasbynens.github.io/rel-noopener/), because web specs give the newly opened window access to the `opener`. The newly opened window could "control the navigation of the original window, and possibly access other DOM objects as well, depending on security policies." ([ref](https://bugs.launchpad.net/mahara/+bug/1558361))

The recommendation is to add `rel="noopener"` to `<a>` tags with a `target` attribute.

**Comment by JoeGermuska** [comment]
However, it appears that this issue has been taken on at a standards level (whatwg/html#4078). 

Specifically, [The rules for choosing a browsing context…](https://whatpr.org/html/4330/browsers.html#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name) in section 7.1.5 of the HTML living standard indicate that `target="_blank"` should yield a new browsing context, except if `rel="opener"` is set. `rel` is not currently stripped, so if we restore `target` (and in any case, in the default iframe embed where `<base target="_blank">` is in effect), then it's possible in principle for someone to override the standard.

So... I think that we could strip `rel` but pass `target` in the sanitizing process.  

Or... DOMPurify supports [making all links open in a new window](https://github.com/cure53/DOMPurify/tree/main/demos#hook-to-open-all-links-in-a-new-window-link), which is almost definitely the right behavior<sup>*</sup>... it would be easy to adapt that example to also make sure that `rel="noopener"` in case someone was trying to override it.

<sup>*</sup> The one exception would be links to other slides, which someone asked about recently. This isn't currently supported because we haven't wired up `hashchange` events (and we default to `target=_blank`)  But it would be easy enough to test the `href` in the DOMPurify hook and implement different behavior for hash-only URLs.

**Comment by JoeGermuska** [comment]
TimelineJS 3.8.12 is released, including a fix for this.

`target` is now a whitelisted attribute which can be specified in markup.

If `target` is not specified, all `a` tags with `href` attributes will have `target="_blank"` added.

All `a` tags with `target="_blank"` (whether originally or added by the TimelineJS code) will also have `rel="noopener"` set, or `noopener` added if for some reason they have a `rel` attribute with other values.
