### ISSUE TITLE
Uncaught TypeError: this.fire is not a function

### ISSUE THREAD

**Issue by amouratoglou** [NUKnightLab/TimelineJS3#651]
```
Uncaught TypeError: this.fire is not a function
    at HTMLDocument._onDataLoaded (Timeline.js:354)
```

Hi guys i'm encountering this error , any known issue?
Using the latest version. It worked normally but suddenly it broke.

**Comment by amouratoglou** [comment]
Just found that it is due to the time it takes to grab from Google Drive, it kinda time-outs and breaks. any workaround? I did a dirty setTimeout to verify this... will try something more elegant, I'm open to suggestions...

**Comment by amouratoglou** [comment]
also noticed some errores with 404 https://knightlab.northwestern.edu/wp-content/uploads/2015/03/front-page-image.jpg
sorry for my messy reporting... i'm running.

**Comment by robinvaughan** [comment]
Yes, every thing was working fine till yesterday but right after this changes - "wait for document content loaded; add soundcite support." the JS broke on my project.

It now just shows Loading Timeline with a revolving image but does not work. Can you please help to fix the issue ASAP as I am using timeline JS heavily in my current project to show timeline carousals.

I believe this newly added code in timeline.js has triggered the error - 

        this._validateOptions();
        if (this.config.isValid()) {
            try {
                if (document.readyState === 'loading') { // Loading hasn't finished yet
                    document.addEventListener('DOMContentLoaded', this._onDataLoaded);
                } else {
                    this._onDataLoaded();
                }

Thanks & Regards,
Robin Vaughan

**Comment by LerouxC** [comment]
Hi everyone!

I am using Timeline js with Drupal through the Views TimelineJS integration module. The timeline has been set up for a few weeks and was working fine until yesterday afternoon. I am getting the same error as amouratoglou . Any help would be very appreciated! Thank you!

**Comment by robinvaughan** [comment]
> Hi everyone!
> 
> I am using Timeline js with Drupal through the Views TimelineJS integration module. The timeline has been set up for a few weeks and was working fine until yesterday afternoon. I am getting the same error as amouratoglou . Any help would be very appreciated! Thank you!

Same here I am also using it on Drupal website Views Timeline JS contributed module using Timeline JS with CDN . It stopped working yesterday after noon.

**Comment by JoeGermuska** [comment]
When reporting issues like this, it is very helpful if you can provide links to documents which demonstrate the issue, and specify the browser and platform in which you encountered the situation.  

As some of you have observed, we introduced a change yesterday, which never manifested these errors in testing. We can roll it back, but it would be best to have test cases, so that we can determine the specifics of the situation and make a more informed choice than simply "undo."

Thanks!

**Comment by JoeGermuska** [comment]
The change which affected you has been reverted. We would still welcome test cases.

**Comment by JoeGermuska** [comment]
[This JSFiddle,](https://jsfiddle.net/tw21635k/) contributed by a Zendesk user, demonstrates the issue, when the Timeline version is set back to 3.7.6

It looks as though there's a binding problem about the value of `this` which only happens in certain circumstances, but which seems to happen consistently in this fiddle. Switching the version between 3.7.6 and 3.7.7/latest makes this clear.

**Comment by JoeGermuska** [comment]
I have a test build that restores the "loaded" check, but explicitly binds the timeline instance as the 'this' for the event handler.

When tested with the JSFiddle above, the timeline now succesfully loads, instead of throwing an error and never getting out of the 'loading' state.

It would be great to have some other tests, though.  If you weighed in above with a situation where the `3.7.6` release of TimelineJS broke yesterday and could try this, we'd be grateful.

To test is as simple as changing `latest` to `dev` in either your embed URL or your TimelineJS `src` url, like these:

https://cdn.knightlab.com/libs/timeline3/dev/embed/index.html?source=1xuY4upIooEeszZ_lCmeNx24eSFWe0rHe9ZdqH2xqVNk&font=Default&lang=en&initial_zoom=2&height=650

https://cdn.knightlab.com/libs/timeline3/dev/js/timeline.js

To further test, you could change `latest` / `dev` to `3.7.6`, which should cause the timeline to fail to load. If `3.7.6` fails and `dev` succeeds, then this would at least be safe to deploy, although whether it helps #653 is TBD

**Comment by JoeGermuska** [comment]
With no input, we've deployed this updated change as `3.7.8`. We're pretty sure this will not cause the issue noted above to occur, but since it hadn't turned up in our original testing and we never found a way to cause it to happen, we'll watch for reports.

**Comment by amouratoglou** [comment]
thanks guys will take a look and revert if i can reproduce again
