### ISSUE TITLE
pictures won't load

### ISSUE THREAD

**Issue by malewis63** [NUKnightLab/TimelineJS3#652]
I have tried multiple solutions. First I hosted all pictures in google drive. They only loaded sometimes. then i uploaded them all to facebook and they loaded fine for about 2 weeks and now they won't load at all. Help. I like your timeline but I can't use it cause the pics won't load.

**Comment by JoeGermuska** [comment]
This question would be better raised through our [online support system](https://knightlab.zendesk.com/hc/en-us/requests/new). Requests for support with specific timelines must include at least the same Google Sheets link used to create the timeline, and, when possible/relevant, a link to the timeline in its published scenario.

That said, neither Google Drive nor Facebook are set up to serve as image hosts. They have specifically implemented technology to interfere with using them this way, which is why things which may appear to work while images are cached or keys haven't timed out eventually fail.

The only general public image hosting services we know which support using images in Timeline with no extra framing or content are Instagram and Flickr.

You can upload images to Imgur.com, but when included in Timeline, they will be surrounded by Imgur "chrome".  Images on Google Drive, shared with "anyone with the link can view" should display in a timeline for as long as they are on drive with that setting, but they will be embedded in a "viewer" which many people would prefer not to have.

It's possible to use Amazon S3 for this, and for many users, they'd never go beyond the free allowances, but that is a fairly technical interface, so we don't generally recommend it.  

Most people who are running content management systems (CMSes) where they will eventually publish their timeline could also use their CMS image library feature, but the specifics may not be obvious to less technical users, and vary too much from CMS to CMS for us to be able to provide support beyond "try right-clicking on images to get a URL you could paste into the 'media' column of your Google sheet"

If you'd like more direct support, again, please use our [online support system](https://knightlab.zendesk.com/hc/en-us/requests/new) and be sure to include the URL to your Google sheet.

**Comment by JoeGermuska** [comment]
FWIW, I just found this [Medium Post](https://blog.usejournal.com/host-static-images-for-your-apps-or-website-on-google-drive-hotlink-to-gdrive-images-358d6fcf8ef7) which describes a way of building a URL for an image hosted on Google Drive which for TimelineJS.

Be aware that this doesn't seem to be officially supported by Google, so may stop working with no warning.
