### ISSUE TITLE
Still "all slides overlapping"

### ISSUE THREAD

**Issue by chepetsk** [NUKnightLab/TimelineJS3#654]
Hi.
We have a problem, which described at https://github.com/NUKnightLab/TimelineJS3/issues/653
it does not always appear. But often. If refresh page - it make OK Timeline.
As we can see in the page code: that when the problem is present, the slides do not have a "left" offset.

Can you help us? Problem page: https://chepetsk.ru/city-history/

**Comment by JoeGermuska** [comment]
Here is what we know about this problem:

In some circumstances, when Timeline is trying to initialize, it doesn't know the width of its container element. This means that it is unable to compute the offsets that space slides out along a horizontal "line" (with all but one outside of the bounds of the container element).  Therefore, all of the slides "stack" or "overlap".

When instantiated, a timeline registers a `resize` event listener on the window. The listener calls the timeline's `updateDisplay` method, which checks the current dimensions of the parent element and redraws all of the elements accordingly. This is why any change to the window size seems to fix the "stacking" problem.

The mystery is why, only sometimes, timelines don't have good information about their container element's dimensions. If we could cause the problem to happen reliably, we could trace the process and try to understand where things are amiss.

So, again, we're much in need of a reliable way of causing the problem to happen. 

**In your specific case:** 
I have seen the overlapping/stacking problem a couple of times, with the link you provided, but not consistently such that I can research the circumstances more thoroughly.

I see a `data-src` attribute on your Timeline `iframe`, and I wonder if that's involved in any kind of "lazy loading" which might set up a situation like the tab circumstance listed above.

**Comment by chepetsk** [comment]
Thanks a lot for your answer. 
No, we don't user lazy loading on this page. Also, I'we tried put Timeline in div container with fix width, but it had no effect.

What if we simulate resize event on our page when document is loaded? Something like this:
var resize = new Event('resize');
window.dispatchEvent(resize);

It can help? Sorry, if sorry if I wrote nonsense :-(

**Comment by JoeGermuska** [comment]
No, that's not nonsense, but I don't think it's the solution, especially because the event in the host window doesn't propagate to the iframe container.  A similar thing you could do would be to change the size of the iframe, even a little, which should have the same effect.

Here's the good news: I've found one place where there was clearly an order-of-events problem which affected the sizing of slides.  There's a similar but different problem with the positioning of the event markers on the navigation component which I'm in the midst of tracking. 

I'm still not 100% sure this will solve issues like yours, since it's so difficult to cause the problem and then see if the new changes solve the problem... but there's a decent chance it will help.

**Comment by chepetsk** [comment]
It worked now! May be this solution is bad, but effective for me:
	$('#history-timeline').on("load", function() {
		var resize = new Event('resize');
		window.dispatchEvent(resize);
		$('#history-timeline').width($('#history-timeline').width()-1);
		$('#history-timeline').width($('#history-timeline').width()+1);
	});

Thank's for your help!

**Comment by JoeGermuska** [comment]
I'm glad that it worked! I guess you were seeing this come up often enough that you feel comfortable that it isn't coming up with that change?

Anyway, I wonder if you would be willing to test the changes I made?  I see that you are currently loading the `dev` version of timeline, which I've just updated, so in this case, testing would just involve disabling your jquery load handler briefly.

Also, I would recommend not leaving your Timeline set to use the `dev` branch, as that is not consistently updated. Not all changes which are published as new versions are published to `/dev/` but they are always published to `/latest/`, so we recommend people use URLs that begin with `https://cdn.knightlab.com/libs/timeline3/latest/` unless there's a specific reason not to.

**Comment by chepetsk** [comment]
I'm sorry, but the changes in the "latest" one had no effect in our case.

**Comment by alissonfpmorais** [comment]
@JoeGermuska I was having a similar problem, and `/dev` branch worked like a charm.
Do you know when these changes are going to be incorporated to `latest`?

Any way, thanks you so much! :)

**Comment by JoeGermuska** [comment]
@alissonfpmorais thanks for the feedback. Since nothing about the changes seems to be negatively impacting things, and it's helpful in at least one case, I've deployed TimelineJS 3.7.9 to be the "latest"

Since right now we're "50/50" on whether these changes solve the issue, I'll leave this open for now.

**Comment by JoeGermuska** [comment]
Closing this in favor of #653 as the main issue tracking this behavior (which has not been reported frequently, if at all, since this change)
