### ISSUE TITLE
marker animation: title and duration out of sync

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#66]
Found this while looking at #41. At certain zoom levels, the transition animation is out of sync for the title and the shaded 'duration' region .

![animated GIF showing sync problem](http://f.cl.ly/items/1p3l1N122V1r0V1D2K2e/Screen%20Recording%202015-03-25%20at%2002.44%20PM.gif)

Screenshot is in Chrome but also verified in Firefox.

**Comment by zachwise** [comment]
Nothing we can do about this. It's the way css animation is handled by the browser. They're just lower in the chain of things to animate so they start and end slightly different from one another despite having the same animation properties given at the same time. You don't see it at larger sizes because the differences are hidden by a background color.

**Comment by zachwise** [comment]
Correction, you don't see it at larger sizes because there is less to animate (ticks) etc so the animation stays in sync more. file this under issue #22

**Comment by zachwise** [comment]
Mainly appears when there is a re-render of the ticks

**Comment by JoeGermuska** [comment]
closing as duplicate of #22
