### ISSUE TITLE
"Error: Timeline configuration has no events" showing up for all timelines, even the template one

### ISSUE THREAD

**Issue by vojtechsedlak** [NUKnightLab/TimelineJS3#667]
It appears that all of our timelines have stopped working and are now displaying the Timeline configuration has no events error, even though no changes were made to them. While the timelines shown on the [Examples](http://timeline.knightlab.com/#examples) page seem to be working, when I made a copy of them, published them and then tried to create new timelines, they would result in the same error. Same goes for the template spreadsheet.

Any insight into what may be causing this issue? 

Example timeline: https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=15JEMy5hSybqF92vgA7qv_1brJy6ecixMgpnEH-VF9KY&font=Default&lang=en&initial_zoom=2&height=650
Source spreadsheet: https://docs.google.com/spreadsheets/d/15JEMy5hSybqF92vgA7qv_1brJy6ecixMgpnEH-VF9KY/edit#gid=0

**Comment by jcnthe1st** [comment]
Having the same issue tonight where the timeline gives the same error even after reverting to the base data in the template. We set a new timeline up with a new template and then had the same issue pop up with the new timeline.

**Comment by stephteague24** [comment]
Same here. Wouldn't even work with the sample template.

**Comment by lordnaickol** [comment]
Hello everybody. 

Same error here. Even using the template spreadsheet without modifications, you got the error.

**Comment by gpakot** [comment]
Hi. Same issue here without any changes in my spreadsheet. I checked no "blank rows" of any kind. If anyone has any idea. I can't get through this on my own I guess
Gwenn

**Comment by Mednikov** [comment]
Hi! Having the same issue. Tried to create a new spreadsheet and the error was the same. But after changing "Share" settings to "Anyone on the internet with this link can **view**" timeline worked. I don't know how safe it is, but it's enough for me for a quick fix.

**Comment by gpakot** [comment]
@Mednikov so grateful you made my day and my Afternoon-keynote 🌈

**Comment by mperezte** [comment]
Ok, thanks Mednikov, hopefully the Knightlab staff will have a safer solution, but thanks again for the quick fix..

**Comment by JoeGermuska** [comment]
Some Google Sheets change has (once again, unfortunately) broken Timeline's ability to call for the configuration data it needs to present a timeline.  

This issue is affecting other people and projects that have nothing to do with TimelineJS, as can be seen in this [Google Support ticket](https://support.google.com/drive/thread/83641755?hl=en)

In the past, this kind of issue is reverted by Google in hours, or sometimes a day or so. There's really nothing else we can do short of substantial re-engineering to TimelineJS, which we're not in a position to do.

As noted above, a consistent workaround seems to be using "share" to set your timeline to "anyone with the link can view".  **Please do not set your timeline to _anyone with the link can edit_** as it is very easy for someone viewing your timeline to work out the URL, and from there, they could vandalize your timeline without you knowing.

Although there's probably nothing we can do about it, we'll leave this issue open until we have some resolution.

**Comment by stephteague24** [comment]
Thank you! That worked.
I am very grateful for your product. It has been a great addition to our
online courses.
Thanks,
Stephanie

**Comment by bforsyth349** [comment]
Setting my timeline to  "anyone with the link can view" no longer solves this problem. Have any other solutions been identified?

**Comment by JoeGermuska** [comment]
@bforsyth349 you must **both** "publish to the web" and "share: anyone with the link can view"

I just made a fresh Google Sheet document and verified that doing both of these allows TimelineJS to read the data.

**Comment by dannguyen** [comment]
FWIW, a recent bug filed to the Issue Tracker relating to Google unexpectedly breaking public published URLs from private Sheets:

https://issuetracker.google.com/issues/173534863

(in one of the duplicate issues, [a Googler says](https://issuetracker.google.com/issues/173651154#comment10) that the above issue is where they'll be posting updates)

**Comment by chepetsk** [comment]
Hi, all! 
My timeline is based by interactive spreadsheet generation under php. And i cant change public settings under webinterface. How can i fix this bug?

**Comment by JoeGermuska** [comment]
@chepetsk are you saying that you are unable to share your Google sheet as "anyone with the link can view"? If that's the case, the only solution I can think of would be to create a new Google Sheets document that you actually own with the same data. Given the nature of this problem that Google has caused, you probably can't download the data as CSV, but you should be able to look at the "pubhtml" version and copy/paste into a new sheet.

**Comment by chepetsk** [comment]
> @chepetsk are you saying that you are unable to share your Google sheet as "anyone with the link can view"? If that's the case, the only solution I can think of would be to create a new Google Sheets document that you actually own with the same data. Given the nature of this problem that Google has caused, you probably can't download the data as CSV, but you should be able to look at the "pubhtml" version and copy/paste into a new sheet.

Hi, Joe!
In my case spreadsheet generated dynamically under php. That means, that i've always had a new document for Timeline. But it doesn't work now!
May be is needed to add some options in my php code for spreadsheet generation? But i dont understand how.

**Comment by JoeGermuska** [comment]
@chepetsk if you mean that your PHP code is generating data and uploading it to Google Sheets, support for that is outside the scope of what we can provide.

**Comment by JoeGermuska** [comment]
Some recent Google change reverted this regression, so that it is not currently necessary to "share" a Google Sheets document for timelines to work.  That said, there is nothing wrong with having shared it, and no action is required. 

Remember, however, that you should **never** share a Timeline Google Sheets document such that "anyone with the link can edit" -- it is not difficult for someone you don't know who is viewing your timeline to construct the URL that would let them take advantage of that setting and change the content of your timeline.
