### ISSUE TITLE
More info overlay

### ISSUE THREAD

**Issue by paul-hammant** [NUKnightLab/TimelineJS3#678]
time.graphics has a feature where you can click on a item in the timeline for an overlay:

![image](https://user-images.githubusercontent.com/82182/104240340-d22b3d80-5453-11eb-8324-e95545595dc3.png)

Or course there's something already in TimelineJS3 for click on item - it moved the timeline to focus on that event.

Is there a possibility of adding something per-event that would trigger an overlay for more info?  Rather than following the href of the main article. Both are needed, but some TimelineJS3 users might prefer an overlay first, and from here, jumps to separate URLs. I'd imagine the to-load overlay is on the same domain, relatively hosted.  For those of use using https://github.com/thecdil/timelinejs-template we would use Markdown/Jekyll for the job.

**Comment by JoeGermuska** [comment]
This seems like an ambitious undertaking, especially when one takes into account the question of responsive design for varied displays, as well as the challenge of specifying configuration of these overlays for the vast majority of our users who are not using (and not going to use) JSON files for configuration.  

Also, I'll note that these overlays exist because the base design of these timelines doesn't allow for prominent presentation of per-event media, while TimelineJS is built around presenting that information first. This comes down to a design decision where time.graphics is prioritizing the relative timing of events, while TimelineJS is emphasizing the event as a building block of a narrative.

**Comment by paul-hammant** [comment]
I've just played with theirs on iOS. It works but is a little clunky. I take your point about prominence. I'd hope that in the fullness of time most of your users are Git-backed :)  I'm not wedded to the JSON format at all. I'd think a hybridized CSV and separate markdown file per event would be better. _Cough, I mean HTML not markdown as that's part of Evan Williamson's (CDIL) Jekyll extensions to TimelineJS3 :)_
