### ISSUE TITLE
JSON Error in Timeline

### ISSUE THREAD

**Issue by Mindtoeye** [NUKnightLab/TimelineJS3#680]
Recently we've started to see the error below displayed in the center of the timeline. The timeline uses a Google spreadsheet which works just fine when tried in the "Make a Timeline" part of the front page. We've stripped out every bit of code other than the timeline code and we verified we're linking to the the same Js and CSS as the one used by the front page, but nothing changes.  Any help would be greatly appreciated!

```
 TypeError: Converting circular structure to JSON
    --&gt; starting at object with constructor 'Je'
    |     property '_nav' -&gt; object with constructor 'Object'
    |     property 'previous' -&gt; object with constructor 'Ve'
    |     ...
    |     index 0 -&gt; object with constructor 'Object'
    --- property 'context' closes the circle
```

**Comment by JoeGermuska** [comment]
If the timeline works on timeline.knightlab.com and not on your site, then it seems the issue is with code on your site. This is something we're unlikely to be able to provide extensive support on, and, of course, without access to a page demonstrating the issue, there's nothing at all we can do.  

But I would take from the message you post that you have not stripped out every bit of code. I don't know what would be trying to convert anything to JSON, but it isn't something TimelineJS would be doing. Can you, instead of stripping things out, build up from a basic page which instantiates a timeline with javascript, and then add back in other features?
