### ISSUE TITLE
Unexpected token / in JSON ?

### ISSUE THREAD

**Issue by thakkaha** [NUKnightLab/TimelineJS3#684]
seems it has stopped working ... console shows the following error

`Uncaught SyntaxError: Unexpected token / in JSON at position 1037`

**Comment by citizenkepler** [comment]
Yeah the issue is that there are javascript comment in the locale JSON files.  As JSON does not support comments this is causing errors processing the JSON.  The files that are causing the issue are the JSON files in this directory:

.//src/js/language/locale/en.json

(For english, but other locales are affected too.)

**Comment by vanmig90** [comment]
Yes , it is creating issue for us, please fix ASAP. We are facing priority issue with this

**Comment by JoeGermuska** [comment]
This issue was fixed earlier today. We apologize for the inconvenience.

**Comment by vanmig90** [comment]
Excellent thanks for the same
