### ISSUE TITLE
Timeline Images not displaying in Chrome Version 89.0.4389.90 (Official Build) (x86_64)

### ISSUE THREAD

**Issue by awfulbliss** [NUKnightLab/TimelineJS3#691]
Having trouble viewing images on our timeline in Chrome. Seems fine in Firefox and Safari right now. 

I just noticed this last week. Any ideas what's going on? Thanks-

**Comment by JoeGermuska** [comment]
We prefer to handle support questions via our [Zendesk system](https://knightlab.zendesk.com/hc/en-us/requests/new), but since this question is here, we can answer it here:

You have not provided the Google Sheets document configuring your timeline, but what you describe is very common. Under Chrome's default security configuration, embedded content, including images, is not loaded if the loading page has an `https` URL and the embedded content has an `http` URL.

By default, the TimelineJS URLs created by the tool at timeline.knightlab.com are `https` URLs, for this very reason -- to use an `http` URL in the `iframe` embed on a page served over `https` would cause the timeline not to appear.

While not all servers handle both `https` and `http` equivalently, for TimelineJS, you can simply change the `https` to `http` -- that is, change
https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1xuY4upIooEeszZ_lCmeNx24eSFWe0rHe9ZdqH2xqVNk&font=Default&lang=en&initial_zoom=2&height=100%
to
http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1xuY4upIooEeszZ_lCmeNx24eSFWe0rHe9ZdqH2xqVNk&font=Default&lang=en&initial_zoom=2&height=100%

Alternatively, you may want to see if you can serve your images and other content referenced in your Google Sheets configuration from an `https` server.

If this turns out not to be the correct diagnosis, please provide the Google Sheets URL to your timeline configuration, either here or in a private message in [Zendesk](https://knightlab.zendesk.com/hc/en-us/requests/new)
