### ISSUE TITLE
Update Lodash from 4.17.9 to 4.17.21

### ISSUE THREAD

**Issue by asipple1** [NUKnightLab/TimelineJS3#697]
Would it be possible to update lodash to 4.17.21? There is a security issue with 4.17.9 that is currently used on the latest CDN url  https://cdn.knightlab.com/libs/timeline3/latest/js/timeline-min.js. Here's a [link](https://snyk.io/vuln/SNYK-JS-LODASH-590103) explaining the exploit.

**Comment by JoeGermuska** [comment]
Thanks for bringing this to our attention. This fix is applied, and will be included in the next release, no later than the end of this week.

**Comment by asipple1** [comment]
Thank you @JoeGermuska! Are you planning on updating the existing CDN link to timeline-min.js or adding a new one?

**Comment by JoeGermuska** [comment]
Our practice is to put versioned releases on the CDN (eg https://cdn.knightlab.com/libs/timeline3/3.8.16/js/timeline-min.js) but also to always make https://cdn.knightlab.com/libs/timeline3/latest/js/timeline-min.js match the most recently released version, so that users of our embed tool automatically get the benefit of updates.

We take backward compatibility seriously, so the versioned release URLs are really meant only as historic record/fallbacks if something goes wrong.

As of Timeline 3.8.0 we are also publishing to `npm` every time we cut a new release.
