### ISSUE TITLE
The Sheets v3 API has been turned down

### ISSUE THREAD

**Issue by snehankekre** [NUKnightLab/TimelineJS3#714]
## Issue
I tried embedding the example from [Step 4 here](https://timeline.knightlab.com/#preview-embed) and noticed the timeline never loads. The same is true true for a [couple of examples](https://mashable.com/archive/timeline-malaysia-airlines-flight-370#x3D;mash-com-Tw-main-link#hzbp7TyJREqX).

Here's screenshots of the relevant 404 request and what happens when you visit the associated spreadsheet URL:
![image](https://user-images.githubusercontent.com/20672874/134864109-8db22b02-d920-4543-afb3-b15c34860218.png)
![image](https://user-images.githubusercontent.com/20672874/134864161-912bf185-bd56-456e-aa7c-c0930cdbf1ea.png)

## Solution
[Migrate from Sheets API v3 to v4](https://developers.google.com/sheets/guides/migration).

**Comment by JoeGermuska** [comment]
To learn more about how Knight Lab prepared for the turndown of the Sheets v3 API, see [this blog post](https://knightlab.northwestern.edu/2020/09/16/timelinejs-update-2/index.html).

In short, we took a path which we believed would allow the most timelines to continue to function with no action required on the part of the creators, as long as they were hosting the timeline using our tool, and using the URL which we have been giving creators by default since the launch of TimelineJS v3 many years ago.

As for the examples, for the ones which don't work, there's nothing we can do except find new examples to replace them. Some of them were from the original version of TimelineJS, which used a URL which stopped automatically updating to the latest version of TimelineJS many years ago, and others may have been locally hosted or otherwise not set up to automatically take advantage of the changes described in the blog post linked above.

You write:
>I tried embedding the example from Step 4 here 
Thank you for drawing to our attention that the default content uses the wrong TimelineJS URL. As soon as someone enters their own Google Sheets URL in step 3, the contents of Step 4 are updated and use the correct URL. We'll update the default case soon.
