### ISSUE TITLE
Failed to fetch: Error fetching CSV

### ISSUE THREAD

**Issue by subrotosanyal** [NUKnightLab/TimelineJS3#722]
Use a published Google sheet to create a timeline.
This use to work but, not working since yesterday.
Even the preview with default sheet on the page http://timeline.knightlab.com/#preview-embed is broken.

**Comment by diogobcp** [comment]
We are having the same issue. 
It seems that the SSL certificate for knightlab.com has expired, as a result the proxy that accesses the Google sheet fails to load because browsers identify the connection as not secure.
We have to wait for Knightlab to renew the certificate.

**Comment by JoeGermuska** [comment]
This issue was resolved earlier this morning.  We apologize for the inconvenience.

GitHub is not the ideal venue for reporting issues like this. We prefer that you use our ZenDesk system ([web form](https://knightlab.zendesk.com/hc/en-us/requests/new) or [email](mailto:support@knightlab.zendesk.com)) or via Twitter with @KnightLab
