### ISSUE TITLE
timeline.min.js and timeline.js are identical?

### ISSUE THREAD

**Issue by jjon** [NUKnightLab/TimelineJS3#723]
Forgive me if I'm missing something obvious, but the [website says:](https://timeline.knightlab.com/docs/instantiate-a-timeline.html)
>If you choose not to load TimelineJS's JavaScript and CSS files from our CDN, you can also load the files locally. To do this, download our ZIP file here.

>Unpack the ZIP and include it on your web server, and load the JS (either timeline.js or timeline.min.js) and CSS (timeline.css) files from it instead of from `cdn.knightlab.com`. If you are using the default fonts and English language, you only need those two files.

But it appears that timeline.min.js and timeline.js are identical (from the zip file here: https://cdn.knightlab.com/libs/timeline3/latest/timeline3.zip). Is that what was intended? I was hoping to work with an un-minified library so I could see how things work.

**Comment by JoeGermuska** [comment]
Since we moved to using webpack to bundle TimelineJS (July 2020, [discussed here](https://knightlab.northwestern.edu/2020/07/09/timelinejs-update/index.html)), it is true that the two files are the same. We aren't in a position to produce a non-minified JS file, but we do create a source map (`timeline3/js/timeline.js.map` in the ZIP archive) which hopefully could serve your purpose.
