### ISSUE TITLE
Problem with Turkish characters in the Headline

### ISSUE THREAD

**Issue by ozan-eo** [NUKnightLab/TimelineJS3#726]
The headlines are automatically converted to capital letters. Some Turkish characters are not correctly displayed when in capital letters.

**Comment by JoeGermuska** [comment]
The handling of headline typography is specific to the font-set chosen. It is true that the default applies a CSS `text-transform: uppercase` but, in fact, most of the font-sets do not.

These are the choices which include the `text-transform: uppercase` directive:

- PT Sans, PT Sans Narrow, and PT Serif (which is the default)
- Old Standard
- Playfair and Fauna One
- Unica One and Vollkorn

While I must admit mostly ignorance about Turkish text, I'll note that the [MDN page for `text-transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) specifically says:

> The text-transform property takes into account language-specific case mapping rules such as the following:
> In Turkic languages, like Turkish (tr), Azerbaijani (az), Crimean Tatar (crh), Volga Tatar (tt), and Bashkir (ba), there are two kinds of i, with and without the dot, and two case pairings: i/İ and ı/I.

which makes we wonder if the issue might not be with the font rather than the CSS.  All of the fonts used are from fonts.google.com which should have more information.  

Finally, while it is a bit involved, it is possible to override the styling of a timeline more completely. See http://timeline.knightlab.com/docs/overriding-styles.html for more information.

**Comment by ozan-eo** [comment]
Filling the headline cells with capital letters in the beginning solved the problem. It seems that the problem is about converting the lowercase letters to capital letters.

**Comment by JoeGermuska** [comment]
interesting. I would think that the message from the MDN page is addressing that kind of thing, but maybe it's an issue with the font not being configured correctly? Really, that kind of thing is far out of my league, but i am happy that you found a solution. Thanks for the update for others who may see this in the future.
