### ISSUE TITLE
The embeddable GoogleDocs words of advice ..

### ISSUE THREAD

**Issue by paul-hammant** [NUKnightLab/TimelineJS3#727]
I wanted to record a video showing how easy it was to drop an embed of timelines (as made by your https://timeline.knightlab.com/#make page), into a wordpress.com site, but the embed doesn't seem to work once saved.  The Inspector's console shows no errors when the timeline doesn't render. In the #make page you can see  the preview working just fine, but not when it goes into the wordpress page in question. I mean save of that page, then switch to viewing is as published. A youtube embed works just fine, by comparison.  I can record a video so you can see what I'm talking about if you like.

**Comment by JoeGermuska** [comment]
Are you using the [TimelineJS plugin for Wordpress](https://wordpress.org/plugins/knight-lab-timelinejs/)?

Typically, Wordpress permissions forbid certain classes of users from entering `<iframe>` tags in the editor. (Specifically, users must have the `unfiltered_html` _capability_ to directly use a TimelineJS iframe embed block.)

The manifestation of this would be that, upon returning to edit the page, the embed would be missing, because, again, WordPress strips it out. The aforementioned plugin solves for this.

If you continue to have issues, this sort of thing is better conducted through our [Zendesk support system](https://knightlab.zendesk.com/hc/en-us/requests/new), and more valuable than a video would be a link to a page manifesting the issue.  

But certainly, many people use TimelineJS on Wordpress sites.

**Comment by paul-hammant** [comment]
Thanks Joe. Through the Workpress.com hosting, plugins require the $33/mo upgrade, so I'll re-do the experiment on something that isn't forcing me upwards from $0/mo
