### ISSUE TITLE
404 not returned https://sheets-proxy.knightlab.com/proxy/

### ISSUE THREAD

**Issue by wilrevehl** [NUKnightLab/TimelineJS3#800]
Hello,

Thank you all so much for maintaining some great little web apps. I have a client with this timeline embed and it seems the proxy  stopped working https://www.firedex.com/about/

I tested the Google Sheets publish settings and compared the embed tutorial to what was on your site. It all seems to line up as it has for a long while now. Here's that link: https://docs.google.com/spreadsheets/d/e/2PACX-1vSrsaqD41C4wqLLDkTMTpd_6gYgI5kGTc6LVMmxwy9y1ee6XtsijbZfRP-t9cmrgDaJNiFUloozNsJv/pubhtml 

Hopefully it is just a temporary outage but wanted to share this in case I'm not the only one. Thanks!

**Comment by JoeGermuska** [comment]
Because we had concerns about our proxy being used as a general purpose proxy for Google Sheets access, there is a rule which requires that access from outside our CDN only retrieve sheets which have the same headers as our template. 

The sheet you sent adds an extra column, triggering this restriction. If removing that (or copying it to a separate worksheet) doesn't address the issue, let us know.

**Comment by wilrevehl** [comment]
That makes sense, thanks. I see what they did there.
