### ISSUE TITLE
Timeline year alias

### ISSUE THREAD

**Issue by zhehenyuhang** [NUKnightLab/TimelineJS3#804]
Is there a custom display_date attribute for the year and date of the timeline, not just for the year but to customize the date format for the specific timeline?

**Comment by JoeGermuska** [comment]
The simplest way to customize a date format is to use the `display_date` property. If using the Google Spreadsheet configuration, this is column **I**. Any text value here will be displayed by TimelineJS instead of running the date through the language-specific date formatter.  Note that you must still specify the date components—year (column A) if nothing else—but this overrides the presentation. See the [docs](http://timeline.knightlab.com/docs/using-spreadsheets.html#dates) for more.

If you didn't want to specify a `display_date` for each slide, you can change the date formatting for all events in a timeline by specifying an alternate "language".  There are two examples of language files that change the default date formatting in this repository: 
* [en-24hr.json](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/language/locale/en-24hr.json)
* [en-week.json](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/language/locale/en-week.json)

This file must be retrievable by a URL. While the value of the `lang` parameter in timeline options, or in a timeline URL, is usually a two-to-five character string, it can also be a URL, as here:

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=https://raw.githubusercontent.com/NUKnightLab/TimelineJS3/master/src/js/language/locale/en-week.json&initial_zoom=2&height=650

Two notes on the above: 
* I see that we must have broken the "week" formatting, because they all show up as "Week W" -- but it still is evidence that the default formatting has been overridden by reading from a URL
* if specifying a URL for a language file (or any other timeline option that accepts URLs), it is recommended to encode the parameter value to avoid any risk of mishandling... so the actual value for `lang` should be `https%3A%2F%2Fraw.githubusercontent.com%2FNUKnightLab%2FTimelineJS3%2Fmaster%2Fsrc%2Fjs%2Flanguage%2Flocale%2Fen-week.json` , but I thought the example was clearer without the URL encoding, and it does actually work in many cases.

(If you were hosting your own copy of the TimelineJS distribution, you could add your language file in `${script_path}/js/language/locale/` and then specify that it be used by putting only the filename, without the extension, as the value of `lang`but not many people do that.)

**Comment by zhehenyuhang** [comment]
Thank you very much. I need to do some research.

**Comment by zhehenyuhang** [comment]
Hello, there is one more thing I need to ask.

Is there a clearer explanation of the language of the options property when manually creating the timeline?

Specifically, json custom changes to language. I'm a little confused about the properties. (I'm so stupid)

Especially for the customization of the year property, sort by year but can the display content be determined by the display_date property?

    "dateformats": {
        "year": "yyyy",
        "month_short": "mmm",
        "month": "mmmm yyyy",
        "full_short": "mmm d",
        "full": "mmmm d',' yyyy",
        "time": "h:MM:ss TT' <small>'mmmm d',' yyyy'</small>'",
        "time_short": "h:MM:ss TT",
        "time_no_seconds_short": "h:MM TT",
        "time_no_minutes_short": "h TT",
        "time_no_seconds_small_date": "h:MM TT' <small>'mmmm d',' yyyy'</small>'",
        "time_milliseconds": "l",
        "full_long": "mmm d',' yyyy 'at' h:MM TT",
        "full_long_small_date": "h:MM TT' <small>mmm d',' yyyy'</small>'"
    },

http://timeline.knightlab.com/docs/options.html


If I'm not being very clear, please forgive me.

**Comment by JoeGermuska** [comment]
Please don't consider yourself stupid because of shortcomings in our documentation, or my communication here. Also, forgive me if the following is too in-depth, but I thought it best to take the opportunity to document this for you and anyone else who might come along, including myself in the future!

I don't suppose there are much clearer explanations than the link you provided. There is another example on the [Instantiating a Timeline](https://timeline.knightlab.com/docs/instantiate-a-timeline.html) page, which is our "intended" starting point for manually creating a timeline. Please be sure to see that, if you haven't.

In general, when creating a timeline in JavaScript, options are a simple JS object. The list of valid "keys" (or "attributes" or "properties") for the object are listed in the [options documentation](http://timeline.knightlab.com/docs/options.html), which you've seen. The valid values are, to our best effort, explained for each key. But, it's not your fault if we haven't been as clear as we could be!

Specifically, you cannot specify date formats directly using options; you can only specify them as part of a language localization file.

Ultimately, though, I must admit that I'm not 100% clear on your question, specifically:
>Especially for the customization of the year property, sort by year but can the display content be determined by the display_date property?

Specifically, I'm not sure what you mean by "sort by year."  Also, as part of manually creating the timeline, are you also using JSON instead of Google Sheets? If so, please be sure you've seen the [TimelineJS JSON data format](http://timeline.knightlab.com/docs/json-format.html) documentation. 

However, reviewing that, I could understand further cause for confusion in that the documentation says that you can specify a `display_date` on a [slide object](http://timeline.knightlab.com/docs/json-format.html#json-slide) and also on a [date object](http://timeline.knightlab.com/docs/json-format.html#json-date)

To be clear, this is not in error. For any given slide, its "canonical display date" is displayed above the headline and text; when a slide has a "next" arrow, that arrow is annotated with the "canonical display date" for the next slide, and similarly for the previous slide. 

The "canonical display date" is derived like so ([link to code](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/slider/Slide.js/#L219-L235)): 
* if the slide has a non-empty `display_date` property, that is used. 
* If it does not, then the "canonical display date" is produced by getting the "canonical display date" for the start date of the slide, and, if the slide has an end date, by getting the same for it, and separating them with an em-dash.  
  * When the slide asks any date object for its "canonical display date" in the slide's `Language` the date responds ([link to code](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/date/TLDate.js/#L188-L205)) with its own `display_date` if it has one. 
  * If it does not, the date uses the provided `Language` to format the date according to the date's data, and, in most cases, a "format key" which is "best" for the level of detail for the given date, as determined when the configuration is processed and the `TLDate` object is constructed ([link to code](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/date/TLDate.js/#L326-L344)).

Hopefully this is not overwhelming detail. Please let us know if you have further questions!

**Comment by zhehenyuhang** [comment]
![image](https://user-images.githubusercontent.com/65812913/199894187-6474b798-2909-4e98-8d70-feb3e9bb97c6.png)
For the text in the red box, we can customize it using the display_date attribute of start_date.

For what I want to say:

Especially for the customization of the year property,  sort by year but can the display content be determined by the display_date property?

Because I don't just want to use the years of our world as the basis for the flow of events.

If I wanted to use this to sort out the events of a novel, their time would be "Y2022", and their time would be prefixed with "Y". I want the user to look at the year in the timeline and see at a glance that the timeline is a summary of the events of that novel.

I don't know if I'm clear.

![image](https://user-images.githubusercontent.com/65812913/199896443-961606e1-b0cb-4783-9e9b-7903e1f6ecbd.png)

Of course, the time is still sequential, but you have what I call a display_date for the timeline on the display. This is only shown as an alias, and I think such an alias might work better for other worlds' timelines. That's just my opinion, of course.

Of course it's best if you can customize it, but it doesn't matter if you don't.

In the document, maybe my understanding is not in place, and I did not find the relevant attributes, so I have to ask these questions. I'm sorry to bother you with some simple questions.

**Comment by zhehenyuhang** [comment]
Thank you for your answer.  I try to provide a new language file and try to modify these two classes to meet my needs.  (At my current level, I will probably fail, hahaha) 
 
If possible, can I put this TimelineJS tool as a part of my graduation project and thesis? 
 
Thank you again for your patient answer.  You have given me a lot of confidence.  Thank you.

**Comment by JoeGermuska** [comment]
Great, good to hear you are feeling confident.  Of course you can use anything you make with TimelineJS however you like. Good luck!
