### ISSUE TITLE
Need URL shortening or abbreviation to prevent text to overflow (Need Joe's regex magic)

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#81]
Possibly regex text and replace urls with abbreviated form to prevent this from happening.
(See screenshot)
![linebreak](https://cloud.githubusercontent.com/assets/741789/7689506/7cb79242-fd72-11e4-89c7-2babbc007eaa.png)

**Comment by zachwise** [comment]
I think we should also make them actual links.

**Comment by JoeGermuska** [comment]
if we do some kind of 'linkify' (which I thought we did, but maybe that hasn't been ported from TimelineJS-orig) then we could also shorten the display URL, so
https://www.flickr.com/photos/zachwise/14514563402/
would be presented as 
[https://www.flickr.com/pho…](https://www.flickr.com/photos/zachwise/14514563402/)

I don't think I'd want to shorten otherwise, but this seems fine...

**Comment by JoeGermuska** [comment]
this seems like the [current best regarded](http://stackoverflow.com/a/21925491/102476) library https://github.com/gregjacobs/Autolinker.js

**Comment by zachwise** [comment]
@JoeGermuska I implemented linkify in the Util class, but I think we should lop-off the `http(s)://` and then ellipsis on a character limit also.
![shorten](https://cloud.githubusercontent.com/assets/741789/7690217/c221732a-fd77-11e4-8033-5992741cfe3f.png)

**Comment by zachwise** [comment]
@JoeGermuska do you want to work your regex magic?

**Comment by JoeGermuska** [comment]
https://docs.google.com/spreadsheets/d/15Y-6SCy6tm5-t-l5N-C7nP1u0fvVRzbS_i-7FluRwmM/pubhtml is a decent testing spreadsheet.
