### ISSUE TITLE
Mobile "swipe to navigate" is not translated to the selected language

### ISSUE THREAD

**Issue by LuOsorio** [NUKnightLab/TimelineJS3#813]
Hi! I'm selecting spanish as the language but this notice is still in English. I couldn't find a way to disable it or to change it in any way. Is there a way to solve this?

Thanks in advance

**Comment by JoeGermuska** [comment]
The issue in this case is that there is no appropriate translation key for that message, which would override [the English language default](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/language/Language.js#L296).

It appears that there is [a version left over from the Spanish translation created for the previous version of TimelineJS](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/language/locale/es.json#L57), which used a different key, and which also didn't have the "OK" text.

So the fix is to adapt the existing translation to the correct translation key, adding the OK note.

We should review all existing translation files to see if we can fix this in as many places as possible. We can start by assuming that "OK" is universally understood, and if people would prefer to submit a translation for that part of it, they can do that in subsequent issues/PRs.
