### ISSUE TITLE
Put media above text on mobile

### ISSUE THREAD

**Issue by 0x6e69636f** [NUKnightLab/TimelineJS3#823]
Hello,
On mobile, the text of an item appears above the media
Is there an option to put it the other away around so the user sees the media just below the date and title ? 
If not, what would be the best way to achieve this : in JS or in CSS ? I can fork the project and propose an edit 

Thanks

Nicolas

**Comment by JoeGermuska** [comment]
Thanks for your interest in contributing to TimelineJS.

If I understand your premise correctly, it's not that there's a bug, but simply that you would prefer the presentation to be different than it is?

Given that the tool has been used to create hundreds of thousands of timelines, we wouldn't accept a pull request which simply changed the behavior of timelines people have created.

You may simply be able to do it by creating an alternative "theme", which is discussed briefly [here](http://timeline.knightlab.com/docs/overriding-styles.html) Note that TimelineJS was created with extremely specific CSS selectors, which makes it difficult to make small changes, because it's not that easy to work out the CSS selectors, so our guess is that it would be easiest to work with the LESS files and compile a complete alternative CSS file. 

Hope this helps. If I misunderstood any of your original post, please steer me in the right direction.
