### ISSUE TITLE
How to destroy/unload media items for memory/CPU considerations?

### ISSUE THREAD

**Issue by object404** [NUKnightLab/TimelineJS3#878]
Hi. New to Timeline JS.

Planning to run it on a Raspberry PI for an interactive kiosk.

Initial testing indicates that it's probably our best solution. I have concerns about handling 300-500 images and videos though.

I tried embedding a video media object in the timeline, and after scrolling forward many slides, then going back to the local MP4 video object, it seems that video objects are not being destroyed or unloaded upon instantiation as the video playhead was still at the position I left it at.

This is a concern if we're going to be loading 300-500 media files in a single timeline on a system with 4-8GB RAM.

Is there a good way to destroy or unload media objects (especially videos) when they go offscreen?

Thanks!

**Comment by JoeGermuska** [comment]
As noted in a few places in our documentation, TimelineJS is designed as a storytelling tool. We made choices optimized around a timeline of 12-20 slides.

We have definitely seen people run timelines with many more events, but we did not take those cases into account when building the software.

Because this is outside of our design parameters, closing this.
