### ISSUE TITLE
"Cannot read property 'checked' of null" in timeline-embed-generator.js

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#94]
Occurs when placing google URL in generator box. Probably why the options selections aren't working.

**Comment by hbillings** [comment]
Okay, `if (e_wordpress.checked)` returns null since removing the WordPress plugin checkbox results. I don't know if we want to just fix the WP plugin checkbox so that it does what it should do, or if we want to remove this check from `Embed.CDN.Generator.js`

**Comment by JoeGermuska** [comment]
I don't know what we're going to do about the Wordpress plugin. I think we'll have to make a new one, because autoupdating the plugin will impact existing deployed timelines on a given wordpress site. This is high impact in a way that even changing which version of the JS is served from timeline.knightlab.com (i.e. the *cutover* milestone) won't change timelines embedded with iframes.

We should just take out this check.

**Comment by hbillings** [comment]
Okay. We're also going to have that issue with the options mentioned in #89 if we need to take those out. So we should figure out which options we aren't going to launch with, and I can comment them out for now.
